import {AutomaticGame,PROMPT} from './automatic.js';
import {DonationEffects,DEFAULT_DONATIONS} from './donations.js';
import {themes,resolveTheme} from './themes.js';
const $=s=>document.querySelector(s);
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',book:'<path d="M12 6c-3-3-7-3-10-1v15c3-2 7-2 10 1 3-3 7-3 10-1V5c-3-2-7-2-10 1zM12 6v15"/>',video:'<rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18M5 6h14M5 18h14"/>',volume:'<path d="m11 4-6 5H2v6h3l6 5zM16 9l5 6M21 9l-5 6"/>',expand:'<path d="M9 3H3v6M15 3h6v6M21 15v6h-6M9 21H3v-6"/>',plus:'<path d="M12 5v14M5 12h14"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',layers:'<path d="m12 3 10 6-10 6L2 9zM2 13l10 6 10-6M2 17l10 6 10-6"/>',settings:'<path d="m9 3-1 3-3 1-2 4 2 2 1 4 3 1 2 3 4-1 1-3 3-1 2-4-2-2-1-4-3-1-2-3z"/><circle cx="12" cy="12" r="3"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m8 4 12 8-12 8z"/>',bulb:'<path d="M9 18h6M10 21h4M8 15a6 6 0 1 1 8 0l-1 3H9z"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.globe}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let configuration={youtube:{videoUrl:'',retrySeconds:15},game:{waitSeconds:15,revealSeconds:3,sounds:true,voice:true,streamMode:false},speech:{language:'ru-RU',rate:.95}};
try{const r=await fetch('/api/config');if(r.ok)configuration=await r.json();}catch{}
configuration.donations={...DEFAULT_DONATIONS,enabled:false,paymentUrl:'',...configuration.donations};
configuration.theme??='classic';
let settings={theme:configuration.theme,delay:configuration.game.revealSeconds*1000,sound:configuration.game.sounds,voice:configuration.game.voice};
try{settings={...settings,...JSON.parse(localStorage.getItem('memo-auto-settings')||'{}')};}catch{}
let controller,effects,pendingToast,audio,chatTimer,chatAbort,connection=0,chatVideo='',cursor=null,suspended=false,renderSignature='';
const chatState=$('#chat-state');
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notify(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(pendingToast);pendingToast=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function saveSettings(){try{localStorage.setItem('memo-auto-settings',JSON.stringify(settings));}catch{}}
function speak(text){if(!settings.voice||!('speechSynthesis' in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=configuration.speech.language;u.rate=configuration.speech.rate;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith(configuration.speech.language.split('-')[0]));if(voice)u.voice=voice;speechSynthesis.speak(u);}catch{}}
function tone(match=false){if(!settings.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=match?880:330;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.start();o.stop(audio.currentTime+.3);}catch{}}
function newController(){controller=new AutomaticGame({now:Date.now,revealMs:settings.delay,waitMs:configuration.game.waitSeconds*1000,onPrompt:()=>speak('Пожалуйста, укажите две карточки.')});effects=new DonationEffects(controller,configuration.donations);}
function buildBoard(){renderSignature='';const game=controller.game;$('#board').innerHTML=game.deck.map(c=>`<button class="card" data-card="${c.id}" disabled><span class="card-inner"><span class="card-back">${themes[resolveTheme(settings.theme)].art}<span class="card-donor"></span><span class="card-number">${String(c.id+1).padStart(2,'0')}</span></span><span class="card-front"><img src="assets/${c.code}.svg" alt="" draggable="false"><span class="country-name">${esc(c.name)}</span><span class="match-check" hidden>✓</span></span></span></button>`).join('');render();}
function render(){const g=controller.game;const phase=controller.phase;const signature=JSON.stringify([g.players,g.selected,g.moves,g.pairs,phase,controller.actor,Math.ceil(controller.remaining()/1000),Math.floor(g.elapsed),g.paused,settings,effects.active,effects.displayName(),effects.queue.length]);if(signature===renderSignature)return;renderSignature=signature;
 const leaders=g.players.map((p,i)=>({...p,index:i})).sort((a,b)=>b.score-a.score);const visible=[{...g.players[0],index:0},...leaders.filter(p=>p.index!==0).slice(0,5)];
 $('#players').innerHTML=visible.map(p=>`<div class="player ${controller.actor===p.index?'current':''}"><span class="avatar">${p.index===0?'🤖':esc(p.name[0])}</span><div class="player-details"><span class="player-name" title="${esc(p.name)}">${esc(p.name)}</span><span class="player-tag">${p.index===0?'Случайный выбор по таймеру':'Личный счёт зрителя'}</span></div><span class="player-score">${p.score}<small>пар</small></span></div>`).join('');
 $('#moves').textContent=g.moves;$('#timer').textContent=`${String(Math.floor(g.elapsed/60)).padStart(2,'0')}:${String(Math.floor(g.elapsed)%60).padStart(2,'0')}`;$('#pairs-found').textContent=g.pairs;$('#progress-fill').style.width=`${g.pairs/26*100}%`;
 $('#turn-status').textContent=phase==='idle'?'Готовы к запуску':phase==='finished'?'Все пары найдены':phase==='waiting'?'Ожидаем ответ зрителей':phase==='peek'?'Все карты открыты':phase==='hint'?'Донат-подсказка':controller.actor===0?'Робот выбирает карточки':`Выбирает ${g.players[controller.actor].name}`;
 $('#instruction').textContent=phase==='peek'?`Бонус от ${effects.active.name}`:phase==='hint'?`Подсветка пары · ${effects.active.name}`:phase==='revealing'?`Карточки ${g.selected.map(i=>i+1).join(' и ')}`:'Автоматическая игра';
 $('#auto-prompt').textContent=phase==='waiting'?PROMPT:phase==='peek'?`${effects.active.name} открывает все карты!`:phase==='hint'?`${effects.active.name}: карта ${effects.active.card+1} открыта, её пара подсвечена`:phase==='revealing'?`${g.players[controller.actor].name}: карточки ${g.selected.map(i=>i+1).join(' и ')}`:phase==='finished'?'Все пары найдены. Игра завершена!':'Запустите игру — дальше всё автоматически';
 $('#countdown').textContent=['waiting','hint','peek'].includes(phase)?Math.ceil(controller.remaining()/1000):phase==='revealing'?'…':configuration.game.waitSeconds;$('#countdown').classList.toggle('urgent',phase==='waiting'&&controller.remaining()<=5000);
 $('#start-auto').hidden=phase!=='idle';$('#auto-hint').textContent=phase==='waiting'?`Напишите в чат два номера, например: 7 24. Нет ответа за ${configuration.game.waitSeconds} сек. — ходит робот.`:phase==='peek'?'Запомните расположение флагов. После показа карты закроются, и начнётся новый раунд.':phase==='hint'?'Запомните флаг и подсвеченный номер. Очко начисляется после выбора пары.':phase==='revealing'?'Совпадение приносит пару тому, кто выбрал карточки.':'Личный счёт каждого зрителя · 26 пар флагов';
 $('#pause-overlay').hidden=!g.paused;$('#pause-button').disabled=['idle','finished'].includes(phase);$('#pause-button').innerHTML=icon(g.paused?'play':'pause')+`<span>${g.paused?'Продолжить':'Пауза'}</span>`;
 $('#sound-button').style.color=settings.sound?'#b6e3b9':'';$('#sound-button').title=settings.sound?'Выключить звуки':'Включить звуки';$('#sound-button').setAttribute('aria-label',$('#sound-button').title);
 $('#board').classList.toggle('all-open',phase==='peek');
 for(const c of g.deck){const el=$(`[data-card="${c.id}"]`);const hint=effects.active;const shown=phase==='peek'||g.selected.includes(c.id)||(hint?.card===c.id),matched=c.matchedBy!==null;el.classList.toggle('hinted-open',hint?.card===c.id);el.classList.toggle('hinted-pair',hint?.pair===c.id);el.querySelector('.card-donor').textContent=effects.displayName();el.querySelector('.card-donor').title=effects.names.join(', ');el.classList.toggle('revealed',shown);el.classList.toggle('matched',matched);el.setAttribute('aria-label',`Карточка ${c.id+1}${shown||matched?': '+c.name:': закрыта'}${matched?', пара найдена':hint?.pair===c.id?', подсвеченная парная карточка':''}`);el.querySelector('.match-check').hidden=!matched;}
 $('#test-choice').disabled=phase!=='waiting'||g.paused;
}
function start(){controller.start();$('#local-message').textContent='';render();}
$('#start-auto').onclick=start;
function restart(){const pending=[...effects.queue,...effects.nextGame];if('speechSynthesis' in window)speechSynthesis.cancel();newController();pending.forEach(event=>effects.receive(event));buildBoard();start();}
function modal(html){suspended=controller.pausedAt===null&& !['idle','finished'].includes(controller.phase);if(suspended)controller.pause();$('#modal-content').innerHTML=html;$('#modal').showModal();render();}
function closeModal(){ $('#modal').close();if(suspended)controller.resume();suspended=false;render(); }
$('#close-modal').onclick=closeModal;$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
$('#new-game').onclick=()=>{if(controller.phase==='idle'){start();return;}modal(`<div class="dialog-eyebrow">НОВАЯ ПАРТИЯ</div><h2>Начать заново?</h2><p>Счёт будет сброшен, а 52 карточки перемешаны. Зрители снова получат 15 секунд на ответ.</p><button class="button primary" id="confirm-restart">Начать новую игру</button>`);$('#confirm-restart').onclick=()=>{closeModal();restart();};};
function pause(){if(controller.game.paused)controller.resume();else controller.pause();render();}$('#pause-button').onclick=pause;$('#resume-button').onclick=pause;
let lastTick=Date.now();setInterval(()=>{const now=Date.now();if(controller.game.started&&!controller.game.paused&&!controller.game.finished){controller.game.elapsed+=(now-lastTick)/1000;}lastTick=now;controller.game.elapsed=Math.round(controller.game.elapsed*1000)/1000;const effectEvent=effects.tick();if(effectEvent?.type==='hint-started')notify(`Подсказка для ${effectEvent.name}${effectEvent.fallback?' — выбранная карта уже собрана, открыта другая':''}`);if(effectEvent?.type==='reveal-all-started')notify(`${effectEvent.name} открывает все карты на ${configuration.donations.revealAllSeconds} секунд!`);const event=controller.tick();if(event==='robot')tone();if(event==='match'||event==='miss'||event==='finished'){const r=controller.result;notify(r.match?`${controller.game.players[r.actor].name}: +1 пара!`:'Флаги разные. Ждём следующий ответ.');if(r.match)tone(true);if(event==='finished')showResults();}render();},100);
function showResults(){const g=controller.game;const max=Math.max(...g.players.map(p=>p.score));const winners=g.players.filter(p=>p.score===max);const title=winners.length>1?'Ничья!':`${winners[0].name} побеждает!`;speak(title);modal(`<span class="result-trophy">🏆</span><h2>${esc(title)}</h2><p>Найдены все 26 пар за ${g.moves} ходов. Участников: ${g.players.length-1}.</p>${[...g.players].sort((a,b)=>b.score-a.score).map(p=>`<div class="result-row"><span>${esc(p.name)}</span><strong>${p.score} пар</strong></div>`).join('')}<button class="button primary" id="play-again">Сыграть ещё раз</button>`);$('#play-again').onclick=()=>{closeModal();restart();};}
function submitMessage(text,viewer,publishedAt){if(controller.submit(text,viewer,publishedAt)){tone();render();return true;}return false;}
$('#local-chat-form').onsubmit=e=>{e.preventDefault();const accepted=submitMessage($('#local-message').value,{id:$('#local-viewer-id').value.trim(),name:$('#local-viewer-name').value.trim()});$('#local-feedback').textContent=accepted?'Выбор зрителей принят.':'Ответ не принят: нужны два разных номера доступных карточек в течение 15 секунд.';if(accepted)$('#local-message').value='';};
async function pollChat(token){if(token!==connection||!chatVideo)return;try{chatAbort=new AbortController();const url=new URL('/api/chat',location.origin);url.searchParams.set('video',chatVideo);if(cursor!==null)url.searchParams.set('after',cursor);const response=await fetch(url,{signal:chatAbort.signal});const data=await response.json();if(token!==connection)return;if(!response.ok)throw Error(data.error||'Не удалось прочитать чат');cursor=data.cursor;chatState.textContent='Чат подключён';chatState.className='chat-connected';
 for(const m of data.messages){const timestamp=Date.parse(m.publishedAt);if(!Number.isFinite(timestamp)||timestamp<controller.roundStarted||timestamp>=controller.deadline||controller.phase!=='waiting')continue;if(submitMessage(m.text,m.viewer,timestamp))break;}
 chatTimer=setTimeout(()=>pollChat(token),Math.max(1000,data.pollAfterMs));
 }catch(e){if(token!==connection)return;chatState.textContent=e.message;chatState.className='chat-error';chatTimer=setTimeout(()=>pollChat(token),configuration.youtube.retrySeconds*1000);}}
$('#connect-chat').onclick=()=>{const input=$('#youtube-url').value.trim();if(!input){notify('Введите ссылку на трансляцию');return;}clearTimeout(chatTimer);chatAbort?.abort();connection++;chatVideo=input;cursor=null;chatState.textContent='Подключаем чат…';chatState.className='';pollChat(connection);};
$('#disconnect-chat').onclick=()=>{clearTimeout(chatTimer);chatAbort?.abort();connection++;chatVideo='';cursor=null;chatState.textContent='Чат не подключён — по таймеру играет робот';chatState.className='';};
function rules(){modal(`<div class="dialog-eyebrow">АВТОМАТИЧЕСКОЕ МЕМО</div><h2>Зрители против робота</h2><ol><li>Нажмите «Запустить игру». Голос попросит указать две карточки, а на экране начнётся отсчёт 15 секунд.</li><li>В подключённом YouTube-чате напишите два номера, например «7 24» или «7, 24». Принимается первое корректное сообщение.</li><li>Если ответа нет, робот случайно выбирает две ещё не найденные карточки, не зная их флагов.</li><li>Совпавшая пара приносит одно очко лично автору сообщения или роботу. Зритель определяется по YouTube-каналу. При несовпадении карточки закрываются на прежних местах.</li><li>После каждого выбора автоматически начинается новый раунд с ожиданием 15 секунд. Когда найдены все пары, показывается победитель.</li></ol><p>Пауза и открытые окна настроек останавливают отсчёт.</p><button class="button primary" id="understood">Понятно</button>`);$('#understood').onclick=closeModal;}
$('#rules-button').onclick=rules;$('#bottom-rules').onclick=rules;
$('#stream-help').onclick=()=>modal(`<div class="dialog-eyebrow">YOUTUBE + OBS</div><h2>Подключение трансляции</h2><ol><li>На сервере задайте YOUTUBE_API_KEY: ключ проекта с включённым YouTube Data API v3, или заполните youtube.apiKey в config.json. Ключ не передаётся в браузер.</li><li>Запустите эфир с открытым чатом и введите ссылку в поле подключения под игровым полем.</li><li>Добавьте окно браузера в OBS и включите «Режим стрима».</li><li>Нажмите «Запустить игру» один раз. Это также разрешает браузеру воспроизводить голос.</li></ol><p>Для озвучивания используется русский голос браузера или системы. Если русского голоса нет, установите его в настройках ОС. Захват звука браузера в OBS должен быть включён.</p><p>Без подключённого чата игра продолжает работать: после 15 секунд выбирает робот. Тестовое поле позволяет проверить ход зрителей без эфира.</p>`);
$('#settings-button').onclick=()=>{modal(`<h2>Настройки</h2><form id="settings-form"><label for="delay">Время показа выбранных карточек</label><select id="delay">${[1800,3000,5000].map(t=>`<option value="${t}" ${settings.delay===t?'selected':''}>${t/1000} сек.</option>`).join('')}</select><label for="voice">Голосовая подсказка</label><select id="voice"><option value="on">Включена</option><option value="off" ${!settings.voice?'selected':''}>Выключена</option></select><label for="sound">Звуковые сигналы</label><select id="sound"><option value="on">Включены</option><option value="off" ${!settings.sound?'selected':''}>Выключены</option></select><p>Ожидание ответа зрителей: ${configuration.game.waitSeconds} секунд (config.json).</p><button class="button primary">Сохранить</button></form>`);$('#settings-form').onsubmit=e=>{e.preventDefault();settings.delay=Number($('#delay').value);settings.voice=$('#voice').value==='on';settings.sound=$('#sound').value==='on';controller.revealMs=settings.delay;if(!settings.voice&&'speechSynthesis' in window)speechSynthesis.cancel();saveSettings();closeModal();};};
$('#sound-button').onclick=()=>{settings.sound=!settings.sound;saveSettings();render();tone();};
$('#fullscreen-button').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Полный экран недоступен');}};
function toggleStream(){const active=document.body.classList.toggle('stream-mode');$('#stream-button').innerHTML=icon('video')+`<span>${active?'Выйти из стрима':'Режим стрима'}</span>`;$('#stream-button').setAttribute('aria-pressed',active);}
$('#stream-button').onclick=toggleStream;$('#nav-game').onclick=()=>$('#board').scrollIntoView({behavior:'smooth'});
newController();buildBoard();applyTheme();

if(configuration.game.streamMode)toggleStream();
if(configuration.youtube.videoUrl){$('#youtube-url').value=configuration.youtube.videoUrl;$('#connect-chat').click();}

function applyTheme(){const id=resolveTheme(settings.theme);document.body.dataset.theme=id;document.querySelectorAll('.card-back .theme-art').forEach(el=>el.outerHTML=themes[id].art);$('#theme-select').value=settings.theme;renderSignature='';render();}
$('#theme-select').innerHTML='<option value="auto">По сезону</option>'+Object.entries(themes).map(([id,t])=>`<option value="${id}">${t.name}</option>`).join('');$('#theme-select').value=settings.theme;
$('#theme-select').onchange=()=>{settings.theme=$('#theme-select').value;saveSettings();applyTheme();};
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:configuration.donations.currency,maximumFractionDigits:2}).format(n);
$('#hint-price').textContent=money(configuration.donations.hintAmount);$('#name-price').textContent=money(configuration.donations.nameAmount);$('#reveal-all-price').textContent=money(configuration.donations.revealAllAmount);$('#reveal-all-offer').textContent=`Все карты лицом вверх на ${configuration.donations.revealAllSeconds} секунд`;
$('#donor-reward option[value="revealAll"]').textContent=`Открыть все карты на ${configuration.donations.revealAllSeconds} секунд`;
if(/^https?:\/\//.test(configuration.donations.paymentUrl)){$('#donate-link').href=configuration.donations.paymentUrl;$('#donate-link').hidden=false;}
$('#donor-reward').onchange=()=>$('#donor-card-label').hidden=$('#donor-reward').value!=='hint';
function receiveDonation(event,test=false){const result=effects.receive(event);if(result.ok){tone(true);notify(`${test?'Тест: ':''}${result.name} — ${result.deferred?'бонус сохранён для следующей партии':result.reward==='name'?'имя на картах до конца партии':result.reward==='revealAll'?'все карты открываются'+(effects.queue.length?' по очереди':''):'подсказка принята'+(effects.queue.length?' в очередь':'')}`);render();}return result;}
$('#donation-test-form').onsubmit=e=>{e.preventDefault();const reward=$('#donor-reward').value;const card=$('#donor-card').value;const event={id:'test-'+(globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random()),name:$('#donor-name').value.trim(),reward,amount:reward==='revealAll'?configuration.donations.revealAllAmount:reward==='hint'?configuration.donations.hintAmount:configuration.donations.nameAmount,currency:configuration.donations.currency,...(reward==='hint'&&card?{card:Number(card)}:{})};const result=receiveDonation(event,true);$('#donation-feedback').textContent=result.ok?'Тестовый эффект применён. Денежный платёж не выполнялся.':result.reason;};
let donationGeneration=0,donationTimer,donationAbort,donationCursor=null,donationToken='';
async function pollDonations(generation){if(generation!==donationGeneration)return;try{donationAbort=new AbortController();const url=new URL('/api/donations/events',location.origin);if(donationCursor!==null)url.searchParams.set('after',donationCursor);const response=await fetch(url,{headers:{Authorization:'Bearer '+donationToken},signal:donationAbort.signal});const data=await response.json();if(generation!==donationGeneration)return;if(!response.ok)throw Error(data.error||'Ошибка подключения донатов');donationCursor=data.cursor;$('#donation-status').textContent=data.provider?.message||'Реальные донаты подключены';$('#donation-status').classList.toggle('chat-error',data.provider?.state==='error');for(const event of data.events){const result=receiveDonation(event);if(!result.ok)$('#donation-status').textContent=result.reason;}donationTimer=setTimeout(()=>pollDonations(generation),1000);}catch(e){if(generation!==donationGeneration)return;$('#donation-status').textContent=e.message;donationTimer=setTimeout(()=>pollDonations(generation),10000);}}
$('#connect-donations').onclick=()=>{donationToken=$('#donation-token').value.trim();if(!donationToken){notify('Введите токен подключения бонусов');return;}clearTimeout(donationTimer);donationAbort?.abort();donationCursor=null;donationGeneration++;$('#donation-status').textContent='Подключаем донат-бонусы…';pollDonations(donationGeneration);};
$('#disconnect-donations').onclick=()=>{clearTimeout(donationTimer);donationAbort?.abort();donationGeneration++;donationToken='';$('#donation-token').value='';$('#donation-status').textContent='Реальные донаты отключены';};

$('#authorize-donationalerts').hidden=configuration.donations.provider!=='donationalerts';
$('#authorize-donationalerts').onclick=async()=>{const token=$('#donation-token').value.trim();if(!token){notify('Введите токен подключения бонусов из config.json');return;}const popup=window.open('about:blank','memo-donationalerts');if(popup){popup.opener=null;popup.document.body.textContent='Подготавливаем вход в DonationAlerts…';}try{const response=await fetch('/api/donations/donationalerts/authorize',{method:'POST',headers:{Authorization:'Bearer '+token}});const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось начать вход');const url=new URL(data.authorizationUrl);if(url.origin!=='https://www.donationalerts.com'||url.pathname!=='/oauth/authorize')throw Error('Некорректный адрес авторизации');if(popup)popup.location.replace(url.toString());else{$('#donationalerts-auth-link').href=url.toString();$('#donationalerts-auth-link').hidden=false;notify('Браузер заблокировал окно: нажмите «Открыть вход DonationAlerts»');}$('#connect-donations').click();}catch(e){if(popup)popup.close();$('#donation-status').textContent=e.message;}};
