import fs from 'node:fs';
const file=process.env.MEMO_CONFIG_PATH||new URL('./config.json',import.meta.url);
export const config=JSON.parse(fs.readFileSync(file,'utf8'));
config.theme??='classic';
config.donations={enabled:false,provider:'webhook',currency:'USD',hintAmount:1,nameAmount:5,revealAllAmount:9.99,hintSeconds:8,revealAllSeconds:8,nameRotationSeconds:5,paymentUrl:'',webhookSecret:'',overlayToken:'',...config.donations};
config.donationAlerts={accessToken:'',refreshToken:'',clientId:'',clientSecret:'',redirectUrl:'http://localhost:3000/api/donations/donationalerts/callback',pollSeconds:5,retrySeconds:30,maxPages:20,...config.donationAlerts};
function between(value,min,max,label){if(!Number.isFinite(value)||value<min||value>max)throw Error(`Некорректный параметр ${label}: допустимо ${min}–${max}`);}
between(config.server.port,1,65535,'server.port');
between(config.game.waitSeconds,1,300,'game.waitSeconds');
between(config.game.revealSeconds,.5,30,'game.revealSeconds');
between(config.youtube.retrySeconds,5,300,'youtube.retrySeconds');
between(config.speech.rate,.1,10,'speech.rate');
between(config.donations.hintAmount,.01,100000,'donations.hintAmount');
between(config.donations.nameAmount,config.donations.hintAmount,100000,'donations.nameAmount');
between(config.donations.revealAllAmount,config.donations.nameAmount,100000,'donations.revealAllAmount');
between(config.donations.hintSeconds,1,60,'donations.hintSeconds');
between(config.donations.revealAllSeconds,1,60,'donations.revealAllSeconds');
between(config.donations.nameRotationSeconds,1,60,'donations.nameRotationSeconds');
between(config.donationAlerts.pollSeconds,5,300,'donationAlerts.pollSeconds');
between(config.donationAlerts.retrySeconds,5,600,'donationAlerts.retrySeconds');
between(config.donationAlerts.maxPages,1,100,'donationAlerts.maxPages');
if(!Number.isInteger(config.donationAlerts.maxPages))throw Error('donationAlerts.maxPages: требуется целое число.');
if(!['webhook','donationalerts'].includes(config.donations.provider))throw Error('donations.provider: выберите donationalerts или webhook.');
if(['accessToken','refreshToken','clientId','clientSecret','redirectUrl'].some(key=>typeof config.donationAlerts[key]!=='string'))throw Error('OAuth-параметры DonationAlerts должны быть строками.');
const redirect=new URL(config.donationAlerts.redirectUrl);
if(!['http:','https:'].includes(redirect.protocol)||redirect.pathname!=='/api/donations/donationalerts/callback'||redirect.search||redirect.hash||redirect.username||redirect.password)throw Error('Проверьте donationAlerts.redirectUrl: требуется адрес callback игры.');
if(redirect.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(redirect.hostname))throw Error('Для удалённого сервера donationAlerts.redirectUrl должен использовать HTTPS.');
if(!/^[A-Z]{3}$/.test(config.donations.currency))throw Error('donations.currency: укажите код валюты, например USD.');
if(['paymentUrl','webhookSecret','overlayToken'].some(key=>typeof config.donations[key]!=='string'))throw Error('Ссылка и секреты подключения донатов должны быть строками.');
if(typeof config.donations.enabled!=='boolean')throw Error('donations.enabled: укажите true или false.');
if(config.donations.paymentUrl&&!/^https?:\/\//.test(config.donations.paymentUrl))throw Error('donations.paymentUrl: требуется ссылка http или https.');
if(typeof config.server.host!=='string'||typeof config.youtube.videoUrl!=='string'||typeof config.youtube.apiKey!=='string')throw Error('Проверьте строковые параметры config.json');
const donations=Object.fromEntries(['enabled','provider','currency','hintAmount','nameAmount','revealAllAmount','hintSeconds','revealAllSeconds','nameRotationSeconds','paymentUrl'].map(key=>[key,config.donations[key]]));
export const publicConfig={youtube:{videoUrl:config.youtube.videoUrl,retrySeconds:config.youtube.retrySeconds},game:config.game,speech:config.speech,theme:config.theme,donations};
