import test from 'node:test';import assert from 'node:assert/strict';import {AutomaticGame,parseChoice} from '../automatic.js';
function setup(random=()=>.3){let t=0,prompts=0;const c=new AutomaticGame({now:()=>t,random,onPrompt:()=>prompts++});return {c,set:v=>t=v,prompts:()=>prompts};}
function pair(c){const a=c.game.deck.find(x=>x.matchedBy===null);return c.game.deck.filter(x=>x.code===a.code).map(x=>x.id+1).join(' ');}
const alice={id:'channel-a',name:'Алиса'},bob={id:'channel-b',name:'Алиса'};
 test('parse two distinct in-range numbers only',()=>{for(const s of ['1 52','1,52','карточки 1 и 52','1 и 52','1:52'])assert.deepEqual(parseChoice(s),[0,51]);for(const s of ['0 1','53 1','1 1','1 2 3','номер 12','hello 1 2','1.5 2'])assert.equal(parseChoice(s),null);});
 test('exact 15-second deadline triggers random two-card robot choice',()=>{const {c,set,prompts}=setup();c.start();assert.equal(prompts(),1);set(14999);assert.equal(c.tick(),null);assert.equal(c.game.selected.length,0);set(15000);assert.equal(c.submit('1 2',alice),false);assert.equal(c.tick(),'robot');assert.equal(c.actor,0);assert.equal(new Set(c.game.selected).size,2);set(18000);c.tick();assert.equal(c.phase,'waiting');assert.equal(c.remaining(),15000);assert.equal(prompts(),2);});
 test('first valid answer wins and every viewer has their own score keyed by channel ID',()=>{const {c,set}=setup();c.start();assert.equal(c.submit('1 1',alice),false);assert.equal(c.game.players.length,1);assert.equal(c.submit(pair(c),alice),true);assert.equal(c.submit('1 2',bob),false);set(3000);assert.equal(c.tick(),'match');assert.equal(c.game.players[1].score,1);assert.equal(c.game.players[0].score,0);assert.equal(c.submit(pair(c),bob),true);set(6000);c.tick();assert.equal(c.game.players.length,3);assert.deepEqual(c.game.players.map(p=>p.score),[0,1,1]);assert.equal(c.submit(pair(c),{...alice,name:'Новое имя'}),true);set(9000);c.tick();assert.equal(c.game.players.length,3);assert.equal(c.game.players[1].name,'Новое имя');assert.equal(c.game.players[1].score,2);});
 test('pause freezes deadlines and ignores chat',()=>{const {c,set}=setup();c.start();set(5000);c.pause();set(25000);assert.equal(c.tick(),null);assert.equal(c.remaining(),10000);assert.equal(c.submit('1 2',alice),false);c.resume();assert.equal(c.remaining(),10000);set(35000);assert.equal(c.tick(),'robot');});
 test('mismatch closes at the same positions; robot match awards robot only',()=>{const {c,set}=setup();c.start();const a=c.game.deck[0],b=c.game.deck.find(x=>x.code!==a.code);const before=c.game.deck.map(x=>x.code);c.submit(`${a.id+1} ${b.id+1}`,alice);set(3000);assert.equal(c.tick(),'miss');assert.deepEqual(c.game.selected,[]);assert.deepEqual(c.game.deck.map(x=>x.code),before);const ids=c.game.deck.filter(x=>x.code===a.code).map(x=>x.id);c.choose(ids,0);set(6000);assert.equal(c.tick(),'match');assert.equal(c.game.players[0].score,1);assert.equal(c.game.players[1].score,0);assert.equal(c.submit(ids.map(i=>i+1).join(' '),alice),false);});
 test('all 26 viewer matches end game without another round',()=>{const {c,set,prompts}=setup();c.start();for(let n=0;n<26;n++){assert.equal(c.submit(pair(c),alice),true);set((n+1)*3000);c.tick();}assert.equal(c.phase,'finished');assert.equal(c.game.players[1].score,26);assert.equal(c.game.players[0].score,0);assert.equal(prompts(),26);assert.equal(c.submit('1 2',alice),false);});
 test('late-delivered messages published during pause are rejected',()=>{const {c,set}=setup();c.start();set(5000);c.pause();set(25000);c.resume();assert.equal(c.submit('1 2',alice,22000),false);assert.equal(c.submit('1 2',alice,-1),false);assert.equal(c.submit('1 2',alice,25000),true);});
