import test from 'node:test';import assert from 'node:assert/strict';import {AutomaticGame} from '../automatic.js';import {DonationEffects,donationReward} from '../donations.js';import {DonationFeed,validSignature,validToken} from '../donation-feed.js';import {createHmac} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
const event=(id,amount=1,extra={})=>({id,name:'Зритель',amount,currency:'USD',...extra});
function setup(){let now=0;const c=new AutomaticGame({now:()=>now,random:()=>.2});const d=new DonationEffects(c);return {c,d,set:t=>now=t};}
 test('amounts and currency select the configured reward',()=>{assert.equal(donationReward(event('a')).reward,'hint');assert.equal(donationReward(event('b',5)).reward,'name');assert.equal(donationReward(event('c',.99)),null);assert.equal(donationReward(event('d',1,{currency:'RUB'})),null);assert.equal(donationReward(event('e',1,{reward:'name'})),null);assert.equal(donationReward(event('f',1,{card:53})),null);assert.equal(donationReward(event('g',1,{message:'карта 12'})).card,12);});
 test('hint opens only one card, highlights its true pair, freezes normal moves, and does not award a point',()=>{const {c,d,set}=setup();c.start();const card=c.game.deck[5];assert.equal(d.receive(event('a',1,{card:6})).ok,true);assert.equal(c.phase,'hint');assert.equal(d.active.card,5);assert.notEqual(d.active.pair,5);assert.equal(c.game.deck[d.active.pair].code,card.code);assert.deepEqual(c.game.selected,[]);assert.equal(c.submit('1 2'),false);set(7999);assert.equal(d.tick(),null);set(8000);assert.equal(d.tick().type,'hint-ended');assert.equal(c.phase,'waiting');assert.equal(c.remaining(),15000);assert.equal(c.game.moves,0);assert.equal(c.game.pairs,0);});
 test('hint queue waits for card resolution and pauses with the game',()=>{const {c,d,set}=setup();c.start();c.submit('1 2');d.receive(event('a'));assert.equal(d.queue.length,1);assert.equal(d.active,null);set(3000);c.tick();d.tick();assert.equal(c.phase,'hint');set(4000);c.pause();set(24000);assert.equal(d.tick(),null);c.resume();set(30999);assert.equal(d.tick(),null);set(31000);assert.equal(d.tick().type,'hint-ended');});
 test('names stay for the whole party and alternate when several donors appear',()=>{const {c,d,set}=setup();c.start();d.receive(event('a',5,{name:'Алиса'}));set(120000);assert.equal(d.displayName(),'Алиса');d.receive(event('b',5,{name:'Борис'}));assert.equal(d.displayName(0),'Алиса');assert.equal(d.displayName(5000),'Борис');assert.equal(d.displayName(10000),'Алиса');assert.equal(d.receive(event('a',5)).ok,false);assert.deepEqual(new DonationEffects(new AutomaticGame()).names,[]);});
 test('matched-card hint falls back to another uncollected card',()=>{const {c,d,set}=setup();c.start();const pair=c.game.deck.filter(x=>x.code===c.game.deck[0].code);c.submit(pair.map(x=>x.id+1).join(' '));set(3000);c.tick();d.receive(event('a',1,{card:1}));assert.equal(d.active.fallback,true);assert.equal(c.game.deck[d.active.card].matchedBy,null);});
 test('paid gifts after game end are retained for the next party',()=>{const {c,d}=setup();c.phase='finished';c.game.finished=true;assert.equal(d.receive(event('a',5)).deferred,true);assert.equal(d.nextGame.length,1);assert.equal(d.receive(event('b')).deferred,true);const next=new DonationEffects(new AutomaticGame());d.nextGame.forEach(e=>assert.equal(next.receive(e).ok,true));assert.deepEqual(next.names,['Зритель']);assert.equal(next.queue.length,1);});
 test('webhook requires HMAC and feed requires the independent overlay token',()=>{const body=JSON.stringify(event('a'));const signature=createHmac('sha256','secret').update(body).digest('hex');assert.equal(validSignature(body,signature,'secret'),true);assert.equal(validSignature(body+' ',signature,'secret'),false);assert.equal(validSignature(body,'wrong','secret'),false);assert.equal(validSignature(body,signature,''),false);assert.equal(validToken('Bearer overlay','overlay'),true);assert.equal(validToken('Bearer wrong','overlay'),false);assert.equal(validToken('Bearer ',''),false);});
 test('event ledger persists and prevents webhook replay across server restarts',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'memo-donations-'));try{const file=path.join(dir,'ledger.json');const first=new DonationFeed({},file);assert.equal(first.receive(event('a')).duplicate,false);assert.equal(first.read(null).events.length,0);const second=new DonationFeed({},file);assert.equal(second.receive(event('a')).duplicate,true);assert.equal(second.read(0).events.length,1);assert.equal(second.receive(event('b',5)).cursor,2);assert.throws(()=>second.receive(event('bad',.1)));}finally{rmSync(dir,{recursive:true,force:true});}});
 test('9.99 USD selects the all-card bonus at its exact price boundary',()=>{assert.equal(donationReward(event('below',9.98)).reward,'name');assert.equal(donationReward(event('exact',9.99)).reward,'revealAll');assert.equal(donationReward(event('above',10)).reward,'revealAll');assert.equal(donationReward(event('insufficient',9.98,{reward:'revealAll'})),null);});
 test('all-card bonus lasts exactly eight seconds, blocks choices and preserves card positions and scores',()=>{const {c,d,set}=setup();c.start();const before=JSON.stringify(c.game.deck);assert.equal(d.receive(event('all',9.99)).reward,'revealAll');assert.equal(c.phase,'peek');assert.equal(c.remaining(),8000);assert.equal(c.submit('1 2'),false);set(7999);assert.equal(d.tick(),null);assert.equal(c.tick(),null);assert.equal(c.phase,'peek');set(8000);assert.equal(d.tick().type,'reveal-all-ended');assert.equal(c.phase,'waiting');assert.equal(c.remaining(),15000);assert.equal(JSON.stringify(c.game.deck),before);assert.equal(c.game.pairs,0);assert.equal(c.game.moves,0);assert.deepEqual(c.game.players.map(p=>p.score),[0]);});
 test('all-card bonus queues during a move and does not overwrite a queued hint',()=>{const {c,d,set}=setup();c.start();c.submit('1 2');d.receive(event('all',9.99));d.receive(event('hint',1));assert.equal(c.phase,'revealing');assert.equal(d.queue.length,2);set(3000);c.tick();assert.equal(d.tick().type,'reveal-all-started');assert.equal(c.phase,'peek');assert.equal(d.queue.length,1);set(11000);assert.equal(d.tick().type,'reveal-all-ended');assert.equal(d.tick().type,'hint-started');assert.equal(c.phase,'hint');});
 test('pausing all-card reveal retains eight seconds of visible play time',()=>{const {c,d,set}=setup();c.start();d.receive(event('all',9.99));set(2000);c.pause();set(22000);assert.equal(d.tick(),null);assert.equal(c.remaining(),6000);c.resume();set(27999);assert.equal(d.tick(),null);set(28000);assert.equal(d.tick().type,'reveal-all-ended');});
 test('all-card bonus after game end is retained for the next party',()=>{const {c,d}=setup();c.phase='finished';assert.equal(d.receive(event('all',9.99)).deferred,true);const nextController=new AutomaticGame(),next=new DonationEffects(nextController);d.nextGame.forEach(e=>next.receive(e));nextController.start();next.tick();assert.equal(nextController.phase,'peek');});
